/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos;

import entidades.articulo.Articulo;
import entidades.articulo.PrecioArticulo;
import entidades.articulo.SubCategoria;
import entidades.articulo.UnidadMedida;
import entidades.cliente.Cliente;

import facade.ArticuloFacade;
import facade.ClienteFacade;
import facade.PrecioArticuloFacade;
import facade.SubCategoriaFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import includes.ExportarExcel;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import vista.cliente.*;

/**
 *
 * @author hugo
 */
public class DiagAdminPrecioArticulo extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private String tipoOperacion;
    private javax.swing.JTextField jTextField;
    private ModeloTablaNoEditable modeloTablaArticuloPrecios;
     private ModeloTablaNoEditable modeloTablaArticulo;
    private Vector headers = new Vector();
    private Vector data = new Vector();
    private Articulo articulo;

    public DiagAdminPrecioArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagAdminPrecioArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodDesc = new javax.swing.ButtonGroup();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticuloPrecio = new javax.swing.JTable();
        jbNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnExportarArt = new javax.swing.JButton();
        btnImportarArt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfArticulo1 = new javax.swing.JTextField();
        jbBuscar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArticulos1 = new javax.swing.JTable();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.jPanel3.border.title"))); // NOI18N

        tblArticuloPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Articulo", "Codigo de Barra", "Lista de Precio", "Precio", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(tblArticuloPrecio);
        if (tblArticuloPrecio.getColumnModel().getColumnCount() > 0) {
            tblArticuloPrecio.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticuloPrecio.columnModel.title0")); // NOI18N
            tblArticuloPrecio.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticuloPrecio.columnModel.title1")); // NOI18N
            tblArticuloPrecio.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticuloPrecio.columnModel.title2")); // NOI18N
            tblArticuloPrecio.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticuloPrecio.columnModel.title3")); // NOI18N
            tblArticuloPrecio.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticuloPrecio.columnModel.title4")); // NOI18N
        }

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jbNuevo.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.jbNuevo.text")); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnExportarArt.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.btnExportarArt.text")); // NOI18N
        btnExportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarArtActionPerformed(evt);
            }
        });

        btnImportarArt.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.btnImportarArt.text")); // NOI18N
        btnImportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarArtActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.jLabel6.text")); // NOI18N

        jbBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        jbBuscar1.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.jbBuscar1.text")); // NOI18N
        jbBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscar1ActionPerformed(evt);
            }
        });

        tblArticulos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Subcategoria", "Unidad de Medida"
            }
        ));
        tblArticulos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblArticulos1MousePressed(evt);
            }
        });
        tblArticulos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblArticulos1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblArticulos1);
        if (tblArticulos1.getColumnModel().getColumnCount() > 0) {
            tblArticulos1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticulos1.columnModel.title0")); // NOI18N
            tblArticulos1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticulos1.columnModel.title1")); // NOI18N
            tblArticulos1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticulos1.columnModel.title2")); // NOI18N
            tblArticulos1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticulos1.columnModel.title3")); // NOI18N
            tblArticulos1.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.tblArticulos1.columnModel.title4")); // NOI18N
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(btnExportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnImportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jbBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbNuevo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnGuardarCambios.setText(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminArticulos.btnGuardarCambios.text")); // NOI18N
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(DiagAdminPrecioArticulo.class, "DiagAdminPrecioArticulo.jPanel3.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarArticluo();
        cargarTablaArticulosPrecios(PrecioArticuloFacade.getInstance().buscarPoridArticulo((long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0)));

        //cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificarArticulo();
        cargarTablaArticulosPrecios(PrecioArticuloFacade.getInstance().buscarPoridArticulo((long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0)));
       // agregarNuevoArticulo(ArticuloFacade.getInstance().getfindArticuloCodigo((long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0)));

        // cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
       if (tblArticulos1.getSelectedRow() != -1) {
        System.out.println("la fila seleccionada es " + (Long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0));
       agregarNuevoArticulo(ArticuloFacade.getInstance().getfindArticuloCodigo((long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0)));
       cargarTablaArticulosPrecios(PrecioArticuloFacade.getInstance().buscarPoridArticulo((long) tblArticulos1.getValueAt(tblArticulos1.getSelectedRow(), 0)));
       }
       else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }
//cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());
        /*if (rbCodigo.isSelected()) {
            //cargarTablaArticulos(ArticuloFacade.getInstance().getTodosCodigo());
        }
        if (rbDescripcion.isSelected()) {
            //cargarTablaArticulos(ArticuloFacade.getInstance().getTodosDescripcion());
        }*/
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void btnExportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarArtActionPerformed
        //Exportar();
    }//GEN-LAST:event_btnExportarArtActionPerformed

    private void btnImportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarArtActionPerformed
       // Importar();
    }//GEN-LAST:event_btnImportarArtActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        guardarArticulos();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void jbBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscar1ActionPerformed
        if (!tfArticulo1.getText().isEmpty()) {
            cargarTablaArticulo(ArticuloFacade.getInstance().buscarPorDescDescCortayCodigo(tfArticulo1.getText()));
        } else {
            cargarTablaArticulo(ArticuloFacade.getInstance().getTodos());
        }
    }//GEN-LAST:event_jbBuscar1ActionPerformed

    private void tblArticulos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticulos1MousePressed
        llenarTabla(tblArticulos1.getSelectedRow());
    }//GEN-LAST:event_tblArticulos1MousePressed

    private void tblArticulos1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblArticulos1KeyReleased
        int key= evt.getKeyCode();
        if(key == KeyEvent.VK_DOWN || key==KeyEvent.VK_UP){
        llenarTabla(tblArticulos1.getSelectedRow());
        }
    }//GEN-LAST:event_tblArticulos1KeyReleased

    private void llenarTabla(Integer filaSelect){
    
    System.out.println("el articulo seleccionado es:" + tblArticulos1.getValueAt(filaSelect, 0) + " " +tblArticulos1.getValueAt(filaSelect, 1) );
    cargarTablaArticulosPrecios(PrecioArticuloFacade.getInstance().buscarPoridArticulo((long) tblArticulos1.getValueAt(filaSelect, 0)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagAdminArticulos dialog = new DiagAdminArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodDesc;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportarArt;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnImportarArt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscar1;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTable tblArticuloPrecio;
    private javax.swing.JTable tblArticulos1;
    private javax.swing.JTextField tfArticulo1;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Administracion de Articulos");
        //this.rbCodigo.setSelected(true);
        
        cargarTablaArticulo(ArticuloFacade.getInstance().getTodos());
    }

    public void cargarTablaArticulosPrecios(List<PrecioArticulo> PrecioArticulos) {
        modeloTablaArticuloPrecios = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulosPrecio(modeloTablaArticuloPrecios);
        //configurarTablaPrecio(tblArticuloPrecio);
        try {
            cargarArticulos(PrecioArticulos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }
     private void cargarTablaArticulo(List<Articulo> articulo) {
        modeloTablaArticulo = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulo(modeloTablaArticulo);
        //configurarTabla(tblArticulos1);
        try {
            cargarArticulostodos(articulo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaArticulosPrecio(ModeloTablaNoEditable modeloTablaArticulosPrecios) {
        modeloTablaArticulosPrecios.addColumn("Id");
        modeloTablaArticulosPrecios.addColumn("Articulo");
        modeloTablaArticulosPrecios.addColumn("Codigo de Barra");
        modeloTablaArticulosPrecios.addColumn("Lista de Precio");
        modeloTablaArticulosPrecios.addColumn("Precio");
        modeloTablaArticulosPrecios.addColumn("Sucursal");
        tblArticuloPrecio.setModel(modeloTablaArticulosPrecios);
    }
      private void cargarEncabezadosTablaArticulo(ModeloTablaNoEditable modeloTablaArticulos) {
        modeloTablaArticulos.addColumn("Codigo");
        modeloTablaArticulos.addColumn("Nombre");
        modeloTablaArticulos.addColumn("Descripcion");
        modeloTablaArticulos.addColumn("Subcategoria");
        modeloTablaArticulos.addColumn("Unidad de Medida");
        tblArticulos1.setModel(modeloTablaArticulos);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }
private void configurarTablaPrecio(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }
    private void cargarArticulos(List<PrecioArticulo> PrecioArticulos) {
        try {
            modeloTablaArticuloPrecios = new ModeloTablaNoEditable();
            cargarEncabezadosTablaArticulosPrecio(modeloTablaArticuloPrecios);
            for (PrecioArticulo precioarticulos : PrecioArticulos) {
                cargarArticulo(precioarticulos);
            }

            tblArticuloPrecio.setModel(modeloTablaArticuloPrecios);
            Comunes.setOcultarColumnasJTable(tblArticuloPrecio, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagAdminArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cargarArticulostodos(List<Articulo> articulo) {
        try {
            modeloTablaArticulo = new ModeloTablaNoEditable();
            cargarEncabezadosTablaArticulo(modeloTablaArticulo);
            for (Articulo articulos : articulo) {
                cargarArticulotodo(articulos);
            }

            tblArticulos1.setModel(modeloTablaArticulo);
            Comunes.setOcultarColumnasJTable(tblArticulos1, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagAdminArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private void cargarArticulo(PrecioArticulo articulos) {

        Object[] fila = new Object[6];
        fila[0] = articulos.getId();
        fila[1] = articulos.getArticulo().getDescripcion();
        fila[2] = articulos.getArticulo().getCodigoBarra();
        fila[3] = articulos.getListaPrecio().getDescripcion();
        fila[4] = articulos.getPrecio();
        fila[5] = articulos.getSucursal().getNombre();
        modeloTablaArticuloPrecios.addRow(fila);
    }
     private void cargarArticulotodo(Articulo articulo) {

      Object[] fila = new Object[6];
        fila[0] = articulo.getId();
        fila[1] = articulo.getCodigoBarra();
        fila[2] = articulo.getDescripcion();
        fila[3] = articulo.getDescripcionReducida();
        fila[4] = articulo.getSubCategoria();
        fila[5] = articulo.getUnidadMedida();
        modeloTablaArticulo.addRow(fila);
    }

    private void modificarArticulo() {
        if (tblArticuloPrecio.getSelectedRow() != -1) {
            PrecioArticulo precioarticulo = PrecioArticuloFacade.getInstance().buscar((Long) tblArticuloPrecio.getValueAt(tblArticuloPrecio.getSelectedRow(), 0));
            DlgPrecioArticulo dlgPrecioArticulo = new DlgPrecioArticulo(null, true, "Modificación", precioarticulo);
            dlgPrecioArticulo.setLocation(Comunes.centrarDialog(dlgPrecioArticulo));
            dlgPrecioArticulo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }

    }

    private void eliminarArticluo() {
        if (tblArticuloPrecio.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el Registro seleccionado?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                try {
                    PrecioArticuloFacade.getInstance().eliminar((Long) tblArticuloPrecio.getValueAt(tblArticuloPrecio.getSelectedRow(), 0));
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e +" :Articulo en uso, no se puede eliminar ");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }
    }

    private void agregarNuevoArticulo(Articulo art) {
        System.out.println("el articulo es" + art.getDescripcion());
        DlgPrecioArticulo diagPrecioArticulo = new DlgPrecioArticulo(null, true, "Alta",art);
        diagPrecioArticulo.setLocation(Comunes.centrarDialog(diagPrecioArticulo));
        diagPrecioArticulo.setVisible(true);
    }

    private void Exportar() {
        new ExportarExcel().crearExcelJtable(tblArticuloPrecio, "Listado de Articulos");
    }

    private void Importar() {
        JFileChooser jChooser = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xls");
        jChooser.setFileFilter(filter);
        jChooser.showOpenDialog(this);
        File file = jChooser.getSelectedFile();
        if (file == null || !file.getName().endsWith("xls")) {
            JOptionPane.showMessageDialog(null, "Please select only Excel file.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            leerDatosExcel(file);
            List<Integer> columnasNoEditables = new ArrayList<>();
            columnasNoEditables.add(0);
            columnasNoEditables.add(1);
            columnasNoEditables.add(2);
            columnasNoEditables.add(3);
            columnasNoEditables.add(4);
            columnasNoEditables.add(5);
            ModeloTablaNoEditable model = new ModeloTablaNoEditable(data, headers, columnasNoEditables);
            tblArticuloPrecio.setModel(model);
        }
    }

    void leerDatosExcel(File file) {
        Workbook workbook = null;
        try {
            try {
                workbook = Workbook.getWorkbook(file);
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
            Sheet sheet = workbook.getSheet(0);
            headers.clear();
            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                headers.add(cell1.getContents());
            }
            data.clear();
            for (int j = 1; j < sheet.getRows(); j++) {
                Vector d = new Vector();
                for (int i = 0; i < sheet.getColumns(); i++) {
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

    private void guardar() {

        int reply = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar los cambios?", "Atualizar Clientes",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                guardarArticulos();
                JOptionPane.showMessageDialog(null, "Clientes actualizados correctamente");
                this.dispose();
            } catch (java.lang.NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "No se han guardado los cambios \n"
                        + "Es posible que haya ingresado un valor incorrecto",
                        "Error Guardando", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se han guardado los cambios");
            this.dispose();
        }

    }

    private void guardarArticulos() {
        try {
            for (int i = 0; i < tblArticuloPrecio.getRowCount(); i++) {

                if (!ArticuloFacade.getInstance().getArticuloCodigo((Long) tblArticuloPrecio.getValueAt(i, 0))) {

                    articulo = new Articulo();

                    articulo.setCodigoBarra(tblArticuloPrecio.getValueAt(i, 1).toString());
                    articulo.setDescripcion(tblArticuloPrecio.getValueAt(i, 2).toString());
                    articulo.setDescripcionReducida(tblArticuloPrecio.getValueAt(i, 3).toString());

                    if (SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticuloPrecio.getValueAt(i, 4)) != null) {
                        articulo.setSubCategoria(SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticuloPrecio.getValueAt(i, 4)));
                    }

                    if (UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticuloPrecio.getValueAt(i, 5)) != null) {
                        articulo.setUnidadMedida(UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticuloPrecio.getValueAt(i, 5)));
                    }

                    ArticuloFacade.getInstance().alta(articulo);

                } else {

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

    }

}
