/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos;

import entidades.articulo.Articulo;
import entidades.articulo.Categoria;
import entidades.articulo.PrecioArticulo;
import facade.ArticuloFacade;
import facade.CategoriaFacade;
import facade.ListaPrecioFacade;
import facade.PrecioArticuloFacade;
import facade.SubCategoriaFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import includes.ExportarExcel;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author hugo
 */
public class DiagPrecios extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private String tipoOperacion;
    private javax.swing.JTextField jTextField;
    private ModeloTablaNoEditable modeloTablaArticulos;
    private Vector headers = new Vector();
    private Vector data = new Vector();
    private Articulo articulo;

    public DiagPrecios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagPrecios(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodDesc = new javax.swing.ButtonGroup();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        labelNombreArticulo = new javax.swing.JLabel();
        tfArticulo = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbRubro = new javax.swing.JRadioButton();
        rbSubRubro = new javax.swing.JRadioButton();
        rbPrecio = new javax.swing.JRadioButton();
        rbPorcentaje = new javax.swing.JRadioButton();
        cbCategoria = new javax.swing.JComboBox();
        labelCategoria = new javax.swing.JLabel();
        labelSubcategoria = new javax.swing.JLabel();
        cboSubCategoria = new javax.swing.JComboBox();
        cboListaPrecios = new javax.swing.JComboBox();
        labelListaPrecios = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jPanel3.border.title"))); // NOI18N

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Descripcion", "Marca", "Categoria", "SubCategoria", "Precio", "L.Precios", "P.Costo", "L.Costo", "Valor(%)"
            }
        ));
        jScrollPane1.setViewportView(tblArticulos);
        if (tblArticulos.getColumnModel().getColumnCount() > 0) {
            tblArticulos.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title0")); // NOI18N
            tblArticulos.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title1")); // NOI18N
            tblArticulos.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title2")); // NOI18N
            tblArticulos.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title3")); // NOI18N
            tblArticulos.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title4")); // NOI18N
            tblArticulos.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title5")); // NOI18N
            tblArticulos.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.tblArticulos.columnModel.title9")); // NOI18N
            tblArticulos.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title6")); // NOI18N
            tblArticulos.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title7")); // NOI18N
            tblArticulos.getColumnModel().getColumn(9).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.tblArticulos.columnModel.title8")); // NOI18N
        }

        labelNombreArticulo.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jLabel5.text")); // NOI18N

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        jbBuscar.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jbBuscar.text")); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.jPanel1.border.title"))); // NOI18N

        bgCodDesc.add(rbRubro);
        rbRubro.setSelected(true);
        rbRubro.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.rbRubro.text")); // NOI18N
        rbRubro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbRubroItemStateChanged(evt);
            }
        });

        bgCodDesc.add(rbSubRubro);
        rbSubRubro.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.rbSubRubro.text")); // NOI18N
        rbSubRubro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSubRubroItemStateChanged(evt);
            }
        });
        rbSubRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSubRubroActionPerformed(evt);
            }
        });

        bgCodDesc.add(rbPrecio);
        rbPrecio.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.rbPrecio.text")); // NOI18N
        rbPrecio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPrecioItemStateChanged(evt);
            }
        });
        rbPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrecioActionPerformed(evt);
            }
        });

        bgCodDesc.add(rbPorcentaje);
        rbPorcentaje.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.rbPorcentaje.text")); // NOI18N
        rbPorcentaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPorcentajeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbRubro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSubRubro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPorcentaje)
                .addGap(4, 4, 4)
                .addComponent(rbPrecio)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbPorcentaje)
                .addComponent(rbPrecio))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbRubro)
                .addComponent(rbSubRubro))
        );

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        labelCategoria.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.labelCategoria.text")); // NOI18N

        labelSubcategoria.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.labelSubcategoria.text")); // NOI18N

        labelListaPrecios.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.labelListaPrecios.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(labelListaPrecios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboListaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(427, 427, 427))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelNombreArticulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(labelCategoria)
                                                .addGap(38, 38, 38))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(labelSubcategoria)
                                                .addGap(26, 26, 26)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboSubCategoria, 0, 212, Short.MAX_VALUE))))
                                .addGap(203, 203, 203))))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubcategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreArticulo)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboListaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListaPrecios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnGuardarCambios.setText(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagAdminArticulos.btnGuardarCambios.text")); // NOI18N
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(DiagPrecios.class, "DiagPrecios.jPanel3.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarArticluo();
        // cargarTablaArticulos(ArticuloFacade.getInstance().getTodos());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificarArticulo();
        cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        if (!tfArticulo.getText().isEmpty()) {
            cargarTablaArticulos(PrecioArticuloFacade.getInstance().buscarPorDescDescCortayCodigo(tfArticulo.getText()));
        } else {
            cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        guardarArticulos();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void rbSubRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSubRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSubRubroActionPerformed

    private void rbPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPrecioActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
       Comunes.cargarJCombo(cboSubCategoria, SubCategoriaFacade.getInstance().buscarPorid((Categoria)cbCategoria.getSelectedItem())); 
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void rbSubRubroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSubRubroItemStateChanged
alternarPorSubrubro();        
        
    }//GEN-LAST:event_rbSubRubroItemStateChanged

    private void rbRubroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbRubroItemStateChanged
       alternarPorRubro();
    }//GEN-LAST:event_rbRubroItemStateChanged

    private void rbPorcentajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPorcentajeItemStateChanged
       alternarPorcentaje();
    }//GEN-LAST:event_rbPorcentajeItemStateChanged

    private void rbPrecioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPrecioItemStateChanged
        alternarPrecio();
    }//GEN-LAST:event_rbPrecioItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagAdminArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagAdminArticulos dialog = new DiagAdminArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodDesc;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JComboBox cboListaPrecios;
    private javax.swing.JComboBox cboSubCategoria;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelListaPrecios;
    private javax.swing.JLabel labelNombreArticulo;
    private javax.swing.JLabel labelSubcategoria;
    private javax.swing.JRadioButton rbPorcentaje;
    private javax.swing.JRadioButton rbPrecio;
    private javax.swing.JRadioButton rbRubro;
    private javax.swing.JRadioButton rbSubRubro;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField tfArticulo;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Administracion de Articulos");
        //this.rbCodigo.setSelected(true);
        labelSubcategoria.setVisible(false);
        cboSubCategoria.setVisible(false);
        labelNombreArticulo.setVisible(false);
        tfArticulo.setVisible(false);
       jbBuscar.setVisible(false);
        Comunes.cargarJCombo(cbCategoria, CategoriaFacade.getInstance().getTodos());
        
        Comunes.cargarJCombo(cboListaPrecios, ListaPrecioFacade.getInstance().getTodos());
        cargarTablaArticulos(PrecioArticuloFacade.getInstance().getTodos());

    }

    private void cargarTablaArticulos(List<PrecioArticulo> precioArticulo) {
        modeloTablaArticulos = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulos(modeloTablaArticulos);
        configurarTabla(tblArticulos);
        try {
            cargarArticulos(precioArticulo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaArticulos(ModeloTablaNoEditable modeloTablaArticulos) {
        modeloTablaArticulos.addColumn("Id");
        modeloTablaArticulos.addColumn("Descripcion");
        modeloTablaArticulos.addColumn("Marca");
        modeloTablaArticulos.addColumn("Categoría");
        modeloTablaArticulos.addColumn("Subcategoria");
        modeloTablaArticulos.addColumn("Precio");
        modeloTablaArticulos.addColumn("L.Precios");
        modeloTablaArticulos.addColumn("P.Costo");
        modeloTablaArticulos.addColumn("L.Costo");
        modeloTablaArticulos.addColumn("Valor(%)");
        tblArticulos.setModel(modeloTablaArticulos);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarArticulos(List<PrecioArticulo> precioArticuloLst) {
        try {
            modeloTablaArticulos = new ModeloTablaNoEditable();
            cargarEncabezadosTablaArticulos(modeloTablaArticulos);
            for (PrecioArticulo precio_articulo : precioArticuloLst) {
                cargarArticulo(precio_articulo);
            }

            tblArticulos.setModel(modeloTablaArticulos);
            Comunes.setOcultarColumnasJTable(tblArticulos, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagAdminArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarArticulo(PrecioArticulo precio_articulo) {

        Object[] fila = new Object[10];
        fila[0] = precio_articulo.getId();
        fila[1] = precio_articulo.getArticulo().getDescripcion();
        fila[2] = precio_articulo.getArticulo().getMarca().getDescripcion();
        fila[3] = precio_articulo.getArticulo().getSubCategoria().getCategoria().getDescripcion();
        fila[4] = precio_articulo.getArticulo().getSubCategoria();
        fila[5] = precio_articulo.getPrecio();
        fila[6] = precio_articulo.getListaPrecio().getDescripcion();
        fila[7] = precio_articulo.getArticulo().getPrecioCosto();

        fila[8] = precio_articulo.getArticulo().getDescuentoCosto().getListaCosto().getDescripcion();
        fila[9] = precio_articulo.getArticulo().getDescuentoCosto().getValor();

        modeloTablaArticulos.addRow(fila);
    }

    private void modificarArticulo() {
        if (tblArticulos.getSelectedRow() != -1) {
            Articulo articulo = ArticuloFacade.getInstance().buscar((Long) tblArticulos.getValueAt(tblArticulos.getSelectedRow(), 0));
            DiagArticulo diagArticulo = new DiagArticulo(null, true, "Modificación", articulo);
            diagArticulo.setLocation(Comunes.centrarDialog(diagArticulo));
            diagArticulo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }

    }

    private void eliminarArticluo() {
        if (tblArticulos.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el Registro seleccionado?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                try {
                    Articulo art = ArticuloFacade.getInstance().buscar((Long) tblArticulos.getValueAt(tblArticulos.getSelectedRow(), 0));

                    for (PrecioArticulo precioArticulo : PrecioArticuloFacade.getInstance().getPreciosArticulo(art)) {
                        PrecioArticuloFacade.getInstance().eliminar(precioArticulo.getId());
                    }
                    ArticuloFacade.getInstance().eliminar((Long) tblArticulos.getValueAt(tblArticulos.getSelectedRow(), 0));
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e + " :Articulo en uso, no se puede eliminar ");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }
    }

    private void agregarNuevoArticulo() {
        DiagArticulo diagArticulo = new DiagArticulo(null, true, "Alta");
        diagArticulo.setLocation(Comunes.centrarDialog(diagArticulo));
        diagArticulo.setVisible(true);
    }

    private void Exportar() {
        new ExportarExcel().crearExcelJtable(tblArticulos, "Listado de Articulos");
    }

    private void Importar() {
        JFileChooser jChooser = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xls");
        jChooser.setFileFilter(filter);
        jChooser.showOpenDialog(this);
        File file = jChooser.getSelectedFile();
        if (file == null || !file.getName().endsWith("xls")) {
            JOptionPane.showMessageDialog(null, "Please select only Excel file.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            leerDatosExcel(file);
            List<Integer> columnasNoEditables = new ArrayList<>();
            columnasNoEditables.add(0);
            columnasNoEditables.add(1);
            columnasNoEditables.add(2);
            columnasNoEditables.add(3);
            columnasNoEditables.add(4);
            columnasNoEditables.add(5);
            ModeloTablaNoEditable model = new ModeloTablaNoEditable(data, headers, columnasNoEditables);
            tblArticulos.setModel(model);
        }
    }

    void leerDatosExcel(File file) {
        Workbook workbook = null;
        try {
            try {
                workbook = Workbook.getWorkbook(file);
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
            Sheet sheet = workbook.getSheet(0);
            headers.clear();
            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                headers.add(cell1.getContents());
            }
            data.clear();
            for (int j = 1; j < sheet.getRows(); j++) {
                Vector d = new Vector();
                for (int i = 0; i < sheet.getColumns(); i++) {
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

    private void guardar() {

        int reply = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar los cambios?", "Atualizar Clientes",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                guardarArticulos();
                JOptionPane.showMessageDialog(null, "Clientes actualizados correctamente");
                this.dispose();
            } catch (java.lang.NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "No se han guardado los cambios \n"
                        + "Es posible que haya ingresado un valor incorrecto",
                        "Error Guardando", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se han guardado los cambios");
            this.dispose();
        }

    }

    private void guardarArticulos() {
        try {
            for (int i = 0; i < tblArticulos.getRowCount(); i++) {

                if (!ArticuloFacade.getInstance().getArticuloCodigo((Long) tblArticulos.getValueAt(i, 0))) {

                    articulo = new Articulo();

                    articulo.setCodigoBarra(tblArticulos.getValueAt(i, 1).toString());
                    articulo.setDescripcion(tblArticulos.getValueAt(i, 2).toString());
                    articulo.setDescripcionReducida(tblArticulos.getValueAt(i, 3).toString());

                    if (SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticulos.getValueAt(i, 4)) != null) {
                        articulo.setSubCategoria(SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticulos.getValueAt(i, 4)));
                    }

                    if (UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticulos.getValueAt(i, 5)) != null) {
                        articulo.setUnidadMedida(UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticulos.getValueAt(i, 5)));
                    }

                    ArticuloFacade.getInstance().alta(articulo);

                } else {

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

    }
    private void alternarPanel() {
       /* pnArticulos.setVisible(!rbTodosLosArticulos.isSelected());
        tfPorcentajeATodos.setVisible(rbTodosLosArticulos.isSelected());
        lblPorcentajeATodos.setVisible(rbTodosLosArticulos.isSelected());
        if (rbAlgunosArticulos.isSelected()) {
            tfPorcentajeATodos.setText("0");
        } else {
            vaciarArticulos();
        }*/
    }

    private void alternarPorSubrubro() {
        labelNombreArticulo.setVisible(!rbSubRubro.isSelected());
          tfArticulo.setVisible(!rbSubRubro.isSelected());
            jbBuscar.setVisible(!rbSubRubro.isSelected());
            labelCategoria.setVisible(rbSubRubro.isSelected());
            cbCategoria.setVisible(rbSubRubro.isSelected());
            labelSubcategoria.setVisible(rbSubRubro.isSelected());
            cboSubCategoria.setVisible(rbSubRubro.isSelected());
        /*lblArticulosDondeSeAplica.setVisible(!rbPrecio.isSelected());
        rbAlgunosArticulos.setVisible(!rbPrecio.isSelected());
        rbTodosLosArticulos.setVisible(!rbPrecio.isSelected());
        lblPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        tfPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        if (rbPrecio.isSelected()) {
            tfPorcentajeATodos.setText("0");
            rbAlgunosArticulos.setSelected(true);
        }
        alternarPanel();*/
    }
       private void alternarPorRubro() {
       labelNombreArticulo.setVisible(!rbSubRubro.isSelected());
          tfArticulo.setVisible(!rbSubRubro.isSelected());
            jbBuscar.setVisible(!rbSubRubro.isSelected());
            labelCategoria.setVisible(rbSubRubro.isSelected());
            cbCategoria.setVisible(rbSubRubro.isSelected());
            labelSubcategoria.setVisible(!rbSubRubro.isSelected());
            cbCategoria.setVisible(!rbSubRubro.isSelected());
        /*lblArticulosDondeSeAplica.setVisible(!rbPrecio.isSelected());
        rbAlgunosArticulos.setVisible(!rbPrecio.isSelected());
        rbTodosLosArticulos.setVisible(!rbPrecio.isSelected());
        lblPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        tfPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        if (rbPrecio.isSelected()) {
            tfPorcentajeATodos.setText("0");
            rbAlgunosArticulos.setSelected(true);
        }
        alternarPanel();*/
    }
          private void alternarPrecio() {
        labelNombreArticulo.setVisible(rbPrecio.isSelected());
          tfArticulo.setVisible(rbPrecio.isSelected());
         jbBuscar.setVisible(rbPrecio.isSelected());
         labelCategoria.setVisible(!rbPrecio.isSelected());
           cbCategoria.setVisible(!rbPrecio.isSelected());
           labelSubcategoria.setVisible(!rbPrecio.isSelected());
           cboSubCategoria.setVisible(!rbPrecio.isSelected());
           
        /*lblArticulosDondeSeAplica.setVisible(!rbPrecio.isSelected());
        rbAlgunosArticulos.setVisible(!rbPrecio.isSelected());
        rbTodosLosArticulos.setVisible(!rbPrecio.isSelected());
        lblPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        tfPorcentajeATodos.setVisible(!rbPrecio.isSelected());
        if (rbPrecio.isSelected()) {
            tfPorcentajeATodos.setText("0");
            rbAlgunosArticulos.setSelected(true);
        }
        alternarPanel();*/
    }
   private void alternarPorcentaje() {
       
     labelNombreArticulo.setVisible(rbPorcentaje.isSelected());
          tfArticulo.setVisible(rbPorcentaje.isSelected());
         jbBuscar.setVisible(rbPorcentaje.isSelected());
         labelCategoria.setVisible(!rbPorcentaje.isSelected());
           cbCategoria.setVisible(!rbPorcentaje.isSelected());
           labelSubcategoria.setVisible(!rbPorcentaje.isSelected());
           cboSubCategoria.setVisible(!rbPorcentaje.isSelected());
    }
}
