/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos;

import entidades.Sucursal;
import entidades.articulo.Articulo;
import entidades.articulo.ListaPrecio;
import entidades.articulo.PrecioArticulo;
import entidades.articulo.SubCategoria;
import entidades.articulo.UnidadMedida;
import facade.ArticuloFacade;
import facade.ListaPrecioFacade;
import facade.PrecioArticuloFacade;
import facade.SubCategoriaFacade;
import facade.SucursalFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import static includes.Comunes.redondear;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import vista.categorias.DiagSubCategoria;

/**
 *
 * @author hugo
 */
public class DlgPrecioArticulo extends javax.swing.JDialog {

    private Articulo articulo;
    private PrecioArticulo precioArticulo;
    private String tipoOperacion;

    /**
     * Creates new form DiagArticulo
     */
    public DlgPrecioArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DlgPrecioArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    public DlgPrecioArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion, Articulo articulo) {
        super(parent, modal);
        initComponents();
        this.articulo = articulo;
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }
    public DlgPrecioArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion, PrecioArticulo precioArticulo) {
        super(parent, modal);
        initComponents();
        this.precioArticulo = precioArticulo;
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfprecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboListaPrecios = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cboSucursal = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.jLabel1.text")); // NOI18N

        tfDescripcion.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.tfDescripcion.text")); // NOI18N

        tfprecio.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.tfprecio.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.jLabel4.text")); // NOI18N

        cboListaPrecios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.jLabel5.text")); // NOI18N

        cboSucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cboSucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboListaPrecios, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(105, 105, 105))
                        .addComponent(tfprecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboListaPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnAceptar.setText(org.openide.util.NbBundle.getMessage(DlgPrecioArticulo.class, "DlgPrecioArticulo.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnAceptar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPrecioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPrecioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPrecioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPrecioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPrecioArticulo dialog = new DlgPrecioArticulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cboListaPrecios;
    private javax.swing.JComboBox cboSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfprecio;
    // End of variables declaration//GEN-END:variables

    private void agregarNuevaSubcategoria() {
        DiagSubCategoria diagSubCategoria = new DiagSubCategoria(null, true, "Alta");
        diagSubCategoria.setLocation(Comunes.centrarDialog(diagSubCategoria));
        diagSubCategoria.setVisible(true);
    }

    private void inicializarComponentes() {
        Comunes.limitarTextField(tfprecio, 30);
        this.setTitle("Articulo");
        Comunes.cargarJCombo(cboListaPrecios, ListaPrecioFacade.getInstance().getTodos());
        Comunes.cargarJCombo(cboSucursal, SucursalFacade.getInstance().getTodos());
        
        //Comunes.cargarJCombo(cboUnidadDeMedida, UnidadMedidaFacade.getInstance().getTodos());
        if (tipoOperacion.equals("Modificación")) {
            cargarDatosArticulo();
        }
        else{tfDescripcion.setText(articulo.getDescripcion());}
    }

    private void aceptar() {
        if (tipoOperacion.equals("Alta")) {
            if (validarArticulo()) {
                precioArticulo = new PrecioArticulo();
                precioArticulo.setArticulo(articulo);
                precioArticulo.setListaPrecio((ListaPrecio)cboListaPrecios.getSelectedItem());
                precioArticulo.setSucursal((Sucursal)cboSucursal.getSelectedItem());
                precioArticulo.setPrecio(redondear(new BigDecimal(tfprecio.getText())));
                
                PrecioArticuloFacade.getInstance().alta(precioArticulo);
                JOptionPane.showMessageDialog(this, "Precio de Articulo agregado!");
                this.dispose();

            }

        } else if (tipoOperacion.equals("Modificación")) {
            if (validarArticulo()) {
                //articulo.setCodigoBarra(tfCodigoBarra.getText().toUpperCase());
               
                precioArticulo.setListaPrecio((ListaPrecio)cboListaPrecios.getSelectedItem());
                precioArticulo.setSucursal((Sucursal)cboSucursal.getSelectedItem());
                precioArticulo.setPrecio(redondear(new BigDecimal(tfprecio.getText())));
                PrecioArticuloFacade.getInstance().modificar(precioArticulo);
                JOptionPane.showMessageDialog(this, "Precio de Articulo modificado!");
                this.dispose();

            }
        }

    }

    private void cargarDatosArticulo() {
        try {
            tfDescripcion.setText(precioArticulo.getArticulo().getDescripcion());
        } catch (Exception e) {

        }
        try {
            tfprecio.setText(precioArticulo.getPrecio().toString());
        } catch (Exception e) {

        }
        try {
           // tfCodigoBarra.setText(articulo.getCodigoBarra());
        } catch (Exception e) {

        }
        try {
            cboListaPrecios.setSelectedItem(precioArticulo.getListaPrecio());
        } catch (Exception e) {

        }
        try {
            cboSucursal.setSelectedItem(precioArticulo.getSucursal());
        } catch (Exception e) {

        }
    }

    private boolean validarArticulo() {
        //boolean flag=Boolean.TRUE;
        if (tfDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El articulo debe tener nombre", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(!Comunes.validarBigDecimal(tfprecio.getText())){
        JOptionPane.showMessageDialog(this, "Debe ingresar el precio en formato numerico", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
      
        }
        
       /* if (tfCodigoBarra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El articulo debe tener Codigo", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        
        if (tipoOperacion.equals("Alta")) {
            if (ArticuloFacade.getInstance().buscarCodigoBarra(tfCodigoBarra.getText())) {
                JOptionPane.showMessageDialog(this, "El codigo de Articulo ya Existe", "Mensaje", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }}*/
        return true;
    }

    private void cargarDatos() {

    }

    private void agregarUnidadMedida() {
        DiagUnidadMedida diagUnidadMedida = new DiagUnidadMedida(null, true, "Alta");
        diagUnidadMedida.setLocationRelativeTo(null);
        diagUnidadMedida.setVisible(true);
    }

    private void eliminarUnidadMedida() {
        int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar Unidad De Medida?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                UnidadMedidaFacade.getInstance().eliminar(((UnidadMedida) cboSucursal.getSelectedItem()).getId());
                JOptionPane.showMessageDialog(null, "Unidad de Medida eliminada");
                Comunes.cargarJCombo(cboSucursal, UnidadMedidaFacade.getInstance().getTodos());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar, unidad de medida en uso!");
            }
        }
    }

    private void eliminarSubcategoria() {
        int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar Subcategoria?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                SubCategoriaFacade.getInstance().eliminar(((SubCategoria) cboListaPrecios.getSelectedItem()).getId());
                JOptionPane.showMessageDialog(null, "Subcategoria eliminada");
                Comunes.cargarJCombo(cboListaPrecios, SubCategoriaFacade.getInstance().getTodos());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar, Subcategoria en uso!");
            }
        }
    }
}
