/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos.stock;

import entidades.articulo.Articulo;
import entidades.articulo.stock.ArticuloDeposito;
import entidades.articulo.stock.Deposito;
import facade.ArticuloDepositoFacade;
import includes.Comunes;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author alumno
 */
public class DiagArticuloDepositoAlta extends javax.swing.JDialog {
  EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
    EntityManager em = emf.createEntityManager();
    Query quArticulo = em.createQuery("SELECT a FROM Articulo a");
    List listArticulo = quArticulo.getResultList();
    Articulo articulo = new Articulo();
    List listArticulosFiltrados;
    Query quDeposito = em.createQuery("SELECT d FROM Deposito d");
    List listDeposito = quDeposito.getResultList();
    ArticuloDeposito articuloDeposito = new ArticuloDeposito();
    ArticuloDepositoFacade ArticuloDepositoFacade;
    /**
     * Creates new form DiagArticuloDepositoAlta
     */
    public DiagArticuloDepositoAlta(java.awt.Frame parent, boolean modal) {
                

        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistArticulosFiltrados = new javax.swing.JList();
        lbDescripcionSeleccionada = new javax.swing.JLabel();
        jXPanel7 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion1 = new javax.swing.JLabel();
        cboDeposito = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        btAsignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jXPanel6.border.title"))); // NOI18N

        lbDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.lbDescripcion.text")); // NOI18N

        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyReleased(evt);
            }
        });

        jlistArticulosFiltrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistArticulosFiltradosMouseClicked(evt);
            }
        });
        jlistArticulosFiltrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistArticulosFiltradosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlistArticulosFiltrados);

        javax.swing.GroupLayout jXPanel6Layout = new javax.swing.GroupLayout(jXPanel6);
        jXPanel6.setLayout(jXPanel6Layout);
        jXPanel6Layout.setHorizontalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addComponent(lbDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                            .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbDescripcionSeleccionada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel6Layout.setVerticalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDescripcionSeleccionada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jXPanel7.border.title"))); // NOI18N

        lbDescripcion1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.lbDescripcion1.text")); // NOI18N

        cboDeposito.setEnabled(false);

        javax.swing.GroupLayout jXPanel7Layout = new javax.swing.GroupLayout(jXPanel7);
        jXPanel7.setLayout(jXPanel7Layout);
        jXPanel7Layout.setHorizontalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDescripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel7Layout.setVerticalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion1)
                    .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jLabel1.text")); // NOI18N

        tfCantidad.setEnabled(false);
        tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCantidadFocusGained(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCantidadKeyReleased(evt);
            }
        });

        btAsignar.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.btAsignar.text")); // NOI18N
        btAsignar.setEnabled(false);
        btAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btAsignar)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyReleased
        filtrarListaArticulos();
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jlistArticulosFiltrados.requestFocus();
            jlistArticulosFiltrados.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tfDescripcionKeyReleased

    private void jlistArticulosFiltradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosMouseClicked
        actualizarArticuloDesdeListaFiltrada();
    }//GEN-LAST:event_jlistArticulosFiltradosMouseClicked

    private void jlistArticulosFiltradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosValueChanged
        actualizarArticuloDesdeListaFiltrada();
        cboDeposito.setEnabled(true);
        tfCantidad.setEnabled(true);
    }//GEN-LAST:event_jlistArticulosFiltradosValueChanged

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
        tfCantidad.selectAll();
    }//GEN-LAST:event_tfCantidadFocusGained

    private void tfCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyPressed

    }//GEN-LAST:event_tfCantidadKeyPressed

    private void tfCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyReleased
        if (!Comunes.validarInteger(tfCantidad.getText())) {
            if (tfCantidad.getText().length() > 1) {
                tfCantidad.setText(tfCantidad.getText().substring(0,
                    tfCantidad.getText().length() - 1));
        } else {
            tfCantidad.setText("");
            btAsignar.setEnabled(false);
        }
        } else {
            btAsignar.setEnabled(true);
        }
    }//GEN-LAST:event_tfCantidadKeyReleased

    private void btAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarActionPerformed
        asignar();
        this.dispose();
    }//GEN-LAST:event_btAsignarActionPerformed
public void inicializarComponentes() {
    this.ArticuloDepositoFacade = ArticuloDepositoFacade.getInstance();
        cargarListaArticuloTodos();
        cargarComboBoxDeposito();
    }

    public void filtrarListaArticulos() {
        emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
        em = emf.createEntityManager();
        quArticulo = em.createQuery("SELECT a FROM Articulo a WHERE a.descripcion LIKE '%" + tfDescripcion.getText() + "%'");
        listArticulosFiltrados = quArticulo.getResultList();
        cargarListaArticulos();
    }

    public void cargarListaArticuloTodos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulo.size(); i++) {
            listaModelo.addElement(listArticulo.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void cargarListaArticulos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulosFiltrados.size(); i++) {
            listaModelo.addElement(listArticulosFiltrados.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void actualizarArticuloDesdeListaFiltrada() {
        articulo = (Articulo) jlistArticulosFiltrados.getSelectedValue();
        lbDescripcionSeleccionada.setText(articulo.toString());
    }

    public void cargarComboBoxDeposito() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listDeposito.size(); i++) {
            modeloCombo.addElement(listDeposito.get(i));
        }
        cboDeposito.setModel(modeloCombo);
    }

    public void asignar() {
        System.out.println("el nombre del articulo es " +(Articulo) jlistArticulosFiltrados.getSelectedValue());
        System.out.println("el nombre del deposito es  " +(Deposito) cboDeposito.getSelectedItem());
        articuloDeposito.setArticulo((Articulo) jlistArticulosFiltrados.getSelectedValue());
        articuloDeposito.setDeposito((Deposito) cboDeposito.getSelectedItem());
        articuloDeposito.setCantidad(Long.parseLong(tfCantidad.getText()));
        ArticuloDepositoFacade.agregarArticulosAlDeposito(articuloDeposito);
        articuloDeposito = new ArticuloDeposito();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagArticuloDepositoAlta dialog = new DiagArticuloDepositoAlta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsignar;
    private javax.swing.JComboBox cboDeposito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private org.jdesktop.swingx.JXPanel jXPanel7;
    private javax.swing.JList jlistArticulosFiltrados;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbDescripcionSeleccionada;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
