/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticuloAlta.java
 *
 * Created on 12/10/2009, 14:29:17
 */
package vista.articulos.stock;


import entidades.persona.CorreoElectronico;
import entidades.persona.Telefono;
import entidades.proveedor.Proveedor;
import facade.ProveedorFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author carlos
 */
public class DiagAdminProveedor extends javax.swing.JDialog {

    List<Telefono> telefonos = new ArrayList<>();
    List<CorreoElectronico> correosElectronicos = new ArrayList<>();

    private String tipoOperacion;

    private ModeloTablaNoEditable modeloTablaProveedores;

    public DiagAdminProveedor(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * Creates new form ArticuloAlta
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Apellido", "Nombre", "Documento"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        setTitle("Alta Deposito");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Proveedor"
            }
        ));
        jScrollPane2.setViewportView(tblProveedores);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarProveedor();
        cargarTablaProveedores(ProveedorFacade.getInstance().getTodos());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        modificarProveedor();
        cargarTablaProveedores(ProveedorFacade.getInstance().getTodos());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
      
         agregarNuevoProveedor();
         cargarTablaProveedores(ProveedorFacade.getInstance().getTodos());
         
    }//GEN-LAST:event_jbNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTable tblProveedores;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
      

        cargarTablaProveedores(ProveedorFacade.getInstance().getTodos());

    }

    /*   public void altaSucursal() {
     try {
     Sucursal sucursal = new Sucursal();
     sucursal.setCodigo(tfCodigo.getText());
     sucursal.setNombre(tfDescripcion.getText());
     Domicilio domicilio = new Domicilio();
     domicilio.setCalle(tfCalle.getText());
     domicilio.setNumero(tfNumero.getText());
     domicilio.setEntreCalles(tfEntreCalles.getText());
     domicilio.setReferencia(tfReferencia.getText());
     domicilio.setBarrio(tfBarrio.getText());
     if(cboLocalidades.getSelectedIndex()!=-1){
     domicilio.setLocalidad((Localidad)cboLocalidades.getSelectedItem());}
     sucursal.setDomicilio(domicilio);
     limpiarTextFields();
     tfDescripcion.requestFocus();
     } catch (NoSuchAlgorithmException ex) {
     Logger.getLogger(frSucursalAlta.class.getName()).log(Level.SEVERE, null, ex);
     }
     }*/
  

    public void cerrarVentana() {
        this.dispose();
    }

   

    private void modificarProveedor() {
  
        if (tblProveedores.getSelectedRow() != -1) {
            Proveedor proveedor = ProveedorFacade.getInstance().buscar((Long) tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 0));
            System.out.println("DEPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOSITO------->" +proveedor);
            DiagProveedor diagAdmProveedor = new DiagProveedor(null, true, "Modificación", proveedor);
            diagAdmProveedor.setLocation(Comunes.centrarDialog(diagAdmProveedor));
            diagAdmProveedor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Proveedor");
        }

    }

    private void eliminarProveedor() {
        if (tblProveedores.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el Registro seleccionado?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                ProveedorFacade.getInstance().eliminar((Long) tblProveedores.getValueAt(tblProveedores.getSelectedRow(), 0));
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Proveedor");
        }
    }

    private void reiniciarListas() {
        telefonos = new ArrayList<>();

        correosElectronicos = new ArrayList<>();

    }

 

    private void cargarTablaProveedores(List<Proveedor> proveedores) {
        modeloTablaProveedores = new ModeloTablaNoEditable();
        cargarEncabezadosTablaProveedores(modeloTablaProveedores);
        configurarTabla(tblProveedores);
        try {
            cargarProveedores(proveedores);
        } catch (Exception ex) {

        }
    }

    private void cargarEncabezadosTablaProveedores(ModeloTablaNoEditable modeloTablaPersonas) {
        modeloTablaPersonas.addColumn("Id");
        modeloTablaPersonas.addColumn("Descripción");

        tblProveedores.setModel(modeloTablaPersonas);
        Comunes.setOcultarColumnasJTable(tblProveedores, 0);
    }

    private void cargarProveedores(List<Proveedor> proveedores) {
        try {
            modeloTablaProveedores = new ModeloTablaNoEditable();
            cargarEncabezadosTablaProveedores(modeloTablaProveedores);
            for (Proveedor proveedor : proveedores) {
                cargarProveedor(proveedor);
            }

            tblProveedores.setModel(modeloTablaProveedores);
        } catch (Exception ex) {
            Logger.getLogger(DiagAdminProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarProveedor(Proveedor proveedor) {

        Object[] fila = new Object[5];
        fila[0] = proveedor.getId();
        fila[1] = proveedor.getDescripcion();

        modeloTablaProveedores.addRow(fila);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void agregarNuevoProveedor() {
        DiagAdminProveedor diagAdmProveedor = new DiagAdminProveedor(null, true, "Alta");
        diagAdmProveedor.setLocation(Comunes.centrarDialog(diagAdmProveedor));
        diagAdmProveedor.setVisible(true);
    }
}
