/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticuloAlta.java
 *
 * Created on 12/10/2009, 14:29:17
 */
package vista.articulos.stock;

import entidades.Sucursal;
import entidades.articulo.Articulo;
import entidades.articulo.stock.ArticuloDeposito;
import entidades.articulo.stock.Deposito;
import facade.ArticuloDepositoFacade;
import facade.ArticuloSucursalFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author carlos
 */
public class DiagArticuloSucursalAlta extends javax.swing.JDialog {

    // Atributos    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
    EntityManager em = emf.createEntityManager();
    Query quArticulo = em.createQuery("SELECT a FROM Articulo a");
    List listArticulo = quArticulo.getResultList();
    Articulo articulo = new Articulo();
    List listArticulosFiltrados;
    Query quDeposito = em.createQuery("SELECT d FROM Deposito d");
    List listDeposito = quDeposito.getResultList();
    Query quPuesto = em.createQuery("SELECT p FROM Sucursal p");
    List listPuesto = quPuesto.getResultList();
    ArticuloDeposito articuloDeposito = new ArticuloDeposito();
    ArticuloSucursalFacade ArticuloSucursalFacade;
    ArticuloDepositoFacade ArticuloDepositoFacade;
    private ModeloTablaNoEditable modeloTablaArticulosAsignar;

    public DiagArticuloSucursalAlta() {

        this.ArticuloSucursalFacade = ArticuloSucursalFacade.getInstance();
        initComponents();
        inicializarComponentes();
    }

    /**
     * Creates new form ArticuloAlta
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistArticulosFiltrados = new javax.swing.JList();
        jXPanel7 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion1 = new javax.swing.JLabel();
        cboDeposito = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jXPanel8 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion2 = new javax.swing.JLabel();
        cboPuesto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        btAsignar = new javax.swing.JButton();
        tfStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArticulosAsignar = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Apellido", "Nombre", "Documento"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        setTitle("Asignar Articulo de Deposito a Sucursal");

        jXPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("ARTICULO"));

        lbDescripcion.setText("Descrip.");

        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyReleased(evt);
            }
        });

        jlistArticulosFiltrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistArticulosFiltradosMouseClicked(evt);
            }
        });
        jlistArticulosFiltrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistArticulosFiltradosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlistArticulosFiltrados);

        javax.swing.GroupLayout jXPanel6Layout = new javax.swing.GroupLayout(jXPanel6);
        jXPanel6.setLayout(jXPanel6Layout);
        jXPanel6Layout.setHorizontalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel6Layout.setVerticalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jXPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloSucursalAlta.jXPanel7.border.title")));

        lbDescripcion1.setText("Descrip.");

        cboDeposito.setEnabled(false);

        jButton1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloSucursalAlta.class, "DiagArticuloDepositoAlta.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel7Layout = new javax.swing.GroupLayout(jXPanel7);
        jXPanel7.setLayout(jXPanel7Layout);
        jXPanel7Layout.setHorizontalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDescripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );
        jXPanel7Layout.setVerticalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion1)
                    .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jXPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloSucursalAlta.class, "DiagArticuloSucursalAlta.jXPanel8.border.title")));

        lbDescripcion2.setText("Descrip.");

        cboPuesto.setEnabled(false);

        javax.swing.GroupLayout jXPanel8Layout = new javax.swing.GroupLayout(jXPanel8);
        jXPanel8.setLayout(jXPanel8Layout);
        jXPanel8Layout.setHorizontalGroup(
            jXPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDescripcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel8Layout.setVerticalGroup(
            jXPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion2)
                    .addComponent(cboPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Cantidad a Asignar");

        tfCantidad.setEnabled(false);
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCantidadKeyReleased(evt);
            }
        });

        btAsignar.setText("Asignar");
        btAsignar.setEnabled(false);
        btAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarActionPerformed(evt);
            }
        });

        tfStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfStock.setEnabled(false);
        tfStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfStockFocusGained(evt);
            }
        });
        tfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStockActionPerformed(evt);
            }
        });
        tfStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfStockKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfStockKeyReleased(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagArticuloSucursalAlta.class, "DiagArticuloDepositoAlta.jLabel2.text")); // NOI18N

        tblArticulosAsignar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículo", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(tblArticulosAsignar);

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(57, 57, 57)
                                        .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)))
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jXPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(192, 192, 192))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3)
                                    .addGap(16, 16, 16)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(85, 85, 85)))
                .addComponent(jXPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAsignar)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(jXPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jXPanel7.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyReleased
        filtrarListaArticulos();
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jlistArticulosFiltrados.requestFocus();
            jlistArticulosFiltrados.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tfDescripcionKeyReleased

    private void jlistArticulosFiltradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosMouseClicked
        actualizarArticuloDesdeListaFiltrada();
    }//GEN-LAST:event_jlistArticulosFiltradosMouseClicked

    private void jlistArticulosFiltradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosValueChanged
        actualizarArticuloDesdeListaFiltrada();
        cboDeposito.setEnabled(true);
        cboPuesto.setEnabled(true);
        tfCantidad.setEnabled(true);
    }//GEN-LAST:event_jlistArticulosFiltradosValueChanged

    private void tfCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyReleased
        if (!Comunes.validarInteger(tfCantidad.getText())) {
            if (tfCantidad.getText().length() > 1) {
                tfCantidad.setText(tfCantidad.getText().substring(0,
                        tfCantidad.getText().length() - 1));
            } else {
                tfCantidad.setText("");
                btAsignar.setEnabled(false);
            }
        } else {
            btAsignar.setEnabled(true);
        }
    }//GEN-LAST:event_tfCantidadKeyReleased

    private void btAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarActionPerformed
        asignar();
        this.dispose();
    }//GEN-LAST:event_btAsignarActionPerformed

    private void tfStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockFocusGained

    private void tfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockActionPerformed

    private void tfStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockKeyPressed

    private void tfStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarStock();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        cargarTablaArticulosAsignar((Articulo) jlistArticulosFiltrados.getSelectedValue(), Long.parseLong(tfCantidad.getText()));
        tfCantidad.setText("");
        tfStock.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) tblArticulosAsignar.getModel(); //TableProducto es el nombre de mi tabla ;) 
        dtm.removeRow(tblArticulosAsignar.getSelectedRow());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         cargarTablaArticulosAsignar((Articulo) jlistArticulosFiltrados.getSelectedValue(), Long.parseLong(tfCantidad.getText()));
        tfCantidad.setText("");
        tfStock.setText("");
        tfDescripcion.requestFocus();
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
         buscarStock();
    }//GEN-LAST:event_jButton1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsignar;
    private javax.swing.JComboBox cboDeposito;
    private javax.swing.JComboBox cboPuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private org.jdesktop.swingx.JXPanel jXPanel7;
    private org.jdesktop.swingx.JXPanel jXPanel8;
    private javax.swing.JList jlistArticulosFiltrados;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbDescripcion2;
    private javax.swing.JTable tblArticulosAsignar;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables

    public void inicializarComponentes() {
        this.ArticuloDepositoFacade = ArticuloDepositoFacade.getInstance();
        cargarListaArticuloTodos();
        cargarComboBoxDeposito();
        cargarComboBoxPuesto();
        modeloTablaArticulosAsignar = new ModeloTablaNoEditable();
       cargarEncabezadosTablaArticulosAsignar(modeloTablaArticulosAsignar);

    }

    public void filtrarListaArticulos() {
        emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
        em = emf.createEntityManager();
        quArticulo = em.createQuery("SELECT a FROM Articulo a WHERE a.descripcion LIKE '%" + tfDescripcion.getText().toUpperCase() + "%'"
                + " OR a.descripcionReducida LIKE '%" + tfDescripcion.getText().toUpperCase() + "%'");
        listArticulosFiltrados = quArticulo.getResultList();
        cargarListaArticulos();
    }

    public void cargarListaArticuloTodos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulo.size(); i++) {
            listaModelo.addElement(listArticulo.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void cargarListaArticulos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulosFiltrados.size(); i++) {
            listaModelo.addElement(listArticulosFiltrados.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void actualizarArticuloDesdeListaFiltrada() {
        articulo = (Articulo) jlistArticulosFiltrados.getSelectedValue();
        //   lbDescripcionSeleccionada.setText(articulo.toString());

    }

    public void cargarComboBoxDeposito() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listDeposito.size(); i++) {
            modeloCombo.addElement(listDeposito.get(i));
        }
        cboDeposito.setModel(modeloCombo);
    }

    public void cargarComboBoxPuesto() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listPuesto.size(); i++) {
            modeloCombo.addElement(listPuesto.get(i));
        }
        cboPuesto.setModel(modeloCombo);
    }

    public void asignar() {
        int fils = tblArticulosAsignar.getRowCount();

        for (int i = 0; i < fils; i++) {
           
            articuloDeposito.setArticulo((Articulo) tblArticulosAsignar.getValueAt(i, 0));
            articuloDeposito.setDeposito((Deposito) cboDeposito.getSelectedItem());
            ArticuloSucursalFacade.transferirArticuloDesdeDepositoASucursal(articuloDeposito, (Sucursal) cboPuesto.getSelectedItem(), (Long) tblArticulosAsignar.getValueAt(i, 1));
            articuloDeposito = new ArticuloDeposito();
        }
/*
        articuloDeposito.setArticulo((Articulo) jlistArticulosFiltrados.getSelectedValue());
        articuloDeposito.setDeposito((Deposito) cboDeposito.getSelectedItem());
        ArticuloSucursalFacade.transferirArticuloDesdeDepositoASucursal(articuloDeposito, (Sucursal) cboPuesto.getSelectedItem(), Long.parseLong(tfCantidad.getText()));
        articuloDeposito = new ArticuloDeposito();
        */
    }

    public void buscarStock() {

        articuloDeposito = ArticuloDepositoFacade.buscar((Articulo) jlistArticulosFiltrados.getSelectedValue(), (Deposito) cboDeposito.getSelectedItem());
        if (articuloDeposito != null) {
            tfStock.setText(articuloDeposito.getCantidad().toString());
        } else {
            tfStock.setText("0");
        }
    }

    private void cargarTablaArticulosAsignar(Articulo art, Long cantidad) {
        
       // configurarTabla(tblArticulosAsignar);
        try {
            cargarArticuloAsignar(art, cantidad);
        } catch (Exception ex) {
            
        }
         tblArticulosAsignar.setModel(modeloTablaArticulosAsignar);
    }
    /*
       private void cargarTablaDepositos(List<Deposito> depositos) {
        modeloTablaDepositos = new ModeloTablaNoEditable();
        cargarEncabezadosTablaDepositos(modeloTablaDepositos);
        configurarTabla(tblDepositos);
        try {
            cargarDepositos(depositos);
        } catch (Exception ex) {

        }
    }
    */

    private void cargarEncabezadosTablaArticulosAsignar(ModeloTablaNoEditable modeloTablaArtAsig) {
        modeloTablaArtAsig.addColumn("Articulo");
        modeloTablaArtAsig.addColumn("Cantidad");

        tblArticulosAsignar.setModel(modeloTablaArtAsig);
        //  Comunes.setOcultarColumnasJTable(tblArticulosAsignar, 0);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarArticuloAsignar(Articulo art, Long cantidad) {

        Object[] fila = new Object[2];
        fila[0] = art;
        fila[1] = cantidad;

        modeloTablaArticulosAsignar.addRow(fila);
        
       

    }
    
}
