/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticuloAlta.java
 *
 * Created on 12/10/2009, 14:29:17
 */
package vista.articulos.stock;

import entidades.articulo.stock.ArticuloDeposito;
import entidades.articulo.stock.ArticuloSucursal;
import entidades.articulo.stock.Deposito;
import entidades.persona.CorreoElectronico;
import entidades.persona.Telefono;
import facade.ArticuloDepositoFacade;
import facade.ArticuloSucursalFacade;
import facade.DepositoFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author carlos
 */
public class DiagStockGeneral extends javax.swing.JDialog {

    List<Telefono> telefonos = new ArrayList<>();
    List<CorreoElectronico> correosElectronicos = new ArrayList<>();

    

    private ModeloTablaNoEditable modeloTablaStockGeneral;

    public DiagStockGeneral(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        inicializarComponentes();
    }

    /**
     * Creates new form ArticuloAlta
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStockGeneral = new javax.swing.JTable();

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Apellido", "Nombre", "Documento"
            }
        ));
        jScrollPane1.setViewportView(tblEmpleados);

        setTitle("Alta Deposito");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblStockGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Articulo", "Stock total", "Sucursal 1", "Sucursal 2", "Deposito 1", "Deposito 2"
            }
        ));
        jScrollPane2.setViewportView(tblStockGeneral);
        if (tblStockGeneral.getColumnModel().getColumnCount() > 0) {
            tblStockGeneral.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblStockGeneral.getColumnModel().getColumn(2).setPreferredWidth(1);
            tblStockGeneral.getColumnModel().getColumn(3).setPreferredWidth(1);
            tblStockGeneral.getColumnModel().getColumn(4).setPreferredWidth(1);
            tblStockGeneral.getColumnModel().getColumn(5).setPreferredWidth(1);
            tblStockGeneral.getColumnModel().getColumn(6).setPreferredWidth(1);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTable tblStockGeneral;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
      

        cargarTablaStockGeneral(ArticuloDepositoFacade.getInstance().getTodos(), ArticuloSucursalFacade.getInstance().getTodos());

    }

    /*   public void altaSucursal() {
     try {
     Sucursal sucursal = new Sucursal();
     sucursal.setCodigo(tfCodigo.getText());
     sucursal.setNombre(tfDescripcion.getText());
     Domicilio domicilio = new Domicilio();
     domicilio.setCalle(tfCalle.getText());
     domicilio.setNumero(tfNumero.getText());
     domicilio.setEntreCalles(tfEntreCalles.getText());
     domicilio.setReferencia(tfReferencia.getText());
     domicilio.setBarrio(tfBarrio.getText());
     if(cboLocalidades.getSelectedIndex()!=-1){
     domicilio.setLocalidad((Localidad)cboLocalidades.getSelectedItem());}
     sucursal.setDomicilio(domicilio);
     limpiarTextFields();
     tfDescripcion.requestFocus();
     } catch (NoSuchAlgorithmException ex) {
     Logger.getLogger(frSucursalAlta.class.getName()).log(Level.SEVERE, null, ex);
     }
     }*/
  

    public void cerrarVentana() {
        this.dispose();
    }

   

    
    private void reiniciarListas() {
        telefonos = new ArrayList<>();

        correosElectronicos = new ArrayList<>();

    }

 

    private void cargarTablaStockGeneral(List<ArticuloDeposito> artDepositos, List<ArticuloSucursal> artSucursal) {
        modeloTablaStockGeneral = new ModeloTablaNoEditable();
        cargarEncabezadosTablaStockGeneral(modeloTablaStockGeneral);
        configurarTabla(tblStockGeneral);
        try {
            cargarStockGeneral(artDepositos, artSucursal);
        } catch (Exception ex) {

        }
    }

    private void cargarEncabezadosTablaStockGeneral(ModeloTablaNoEditable modeloTablaPersonas) {
        modeloTablaPersonas.addColumn("Id");
        modeloTablaPersonas.addColumn("Artículo");
        modeloTablaPersonas.addColumn("Stock Total");
        modeloTablaPersonas.addColumn("Sucursal 1");
        modeloTablaPersonas.addColumn("Sucursal 2");
        modeloTablaPersonas.addColumn("Depósito 1");
        modeloTablaPersonas.addColumn("Depósito 2");
        

        tblStockGeneral.setModel(modeloTablaPersonas);
        Comunes.setOcultarColumnasJTable(tblStockGeneral, 0);
    }

    private void cargarStockGeneral(List<ArticuloDeposito> artDepositos, List<ArticuloSucursal> artSucursal) {
        try {
            modeloTablaStockGeneral = new ModeloTablaNoEditable();
            cargarEncabezadosTablaStockGeneral(modeloTablaStockGeneral);
           /* for (Deposito deposito : depositos) {
                cargarDeposito(deposito);
            }*/

            tblStockGeneral.setModel(modeloTablaStockGeneral);
        } catch (Exception ex) {
            Logger.getLogger(DiagStockGeneral.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarDeposito(ArticuloDeposito artDeposito, ArticuloSucursal artSucursal ) {

        Object[] fila = new Object[5];
      //  fila[0] = deposito.getId();
      //  fila[1] = deposito.getDescripcion();

        modeloTablaStockGeneral.addRow(fila);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

   
}
