/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos.stock;

import entidades.Sucursal;
import entidades.articulo.Articulo;
import entidades.articulo.stock.ArticuloDeposito;
import entidades.articulo.stock.ArticuloDepositoMovimiento;
import entidades.articulo.stock.Deposito;
import facade.ArticuloDepositoFacade;
import facade.ArticuloDepositoMovimientoFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class DiagArticuloDepositoAlta extends javax.swing.JDialog {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
    EntityManager em = emf.createEntityManager();
    Query quArticulo = em.createQuery("SELECT a FROM Articulo a");
    List listArticulo = quArticulo.getResultList();
    Articulo articulo = new Articulo();
    List listArticulosFiltrados;
    Query quDeposito = em.createQuery("SELECT d FROM Deposito d");
    List listDeposito = quDeposito.getResultList();
    ArticuloDeposito articuloDeposito = new ArticuloDeposito();
    ArticuloDepositoMovimiento articuloDepositoMovimiento = new ArticuloDepositoMovimiento();
    ArticuloDepositoFacade ArticuloDepositoFacade;
    ArticuloDepositoMovimientoFacade ArticuloDepositoMovimientoFacade;
    private ModeloTablaNoEditable modeloTablaArticulosAsignar;
    int numLote = 0;

    /**
     * Creates new form DiagArticuloDepositoAlta
     */
    public DiagArticuloDepositoAlta(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistArticulosFiltrados = new javax.swing.JList();
        lbDescripcionSeleccionada = new javax.swing.JLabel();
        jXPanel7 = new org.jdesktop.swingx.JXPanel();
        lbDescripcion1 = new javax.swing.JLabel();
        cboDeposito = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        btAsignar = new javax.swing.JButton();
        tfStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArticulosAsignar = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jbconfirmar = new javax.swing.JButton();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfactura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jXPanel6.border.title"))); // NOI18N

        lbDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.lbDescripcion.text")); // NOI18N

        tfDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescripcionActionPerformed(evt);
            }
        });
        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyReleased(evt);
            }
        });

        jlistArticulosFiltrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistArticulosFiltradosMouseClicked(evt);
            }
        });
        jlistArticulosFiltrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlistArticulosFiltradosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlistArticulosFiltrados);

        javax.swing.GroupLayout jXPanel6Layout = new javax.swing.GroupLayout(jXPanel6);
        jXPanel6.setLayout(jXPanel6Layout);
        jXPanel6Layout.setHorizontalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jXPanel6Layout.createSequentialGroup()
                                .addComponent(lbDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbDescripcionSeleccionada))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jXPanel6Layout.setVerticalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescripcionSeleccionada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jXPanel7.border.title"))); // NOI18N

        lbDescripcion1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.lbDescripcion1.text")); // NOI18N

        cboDeposito.setEnabled(false);

        javax.swing.GroupLayout jXPanel7Layout = new javax.swing.GroupLayout(jXPanel7);
        jXPanel7.setLayout(jXPanel7Layout);
        jXPanel7Layout.setHorizontalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDescripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel7Layout.setVerticalGroup(
            jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripcion1)
                    .addComponent(cboDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jLabel1.text")); // NOI18N

        tfCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCantidad.setEnabled(false);
        tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCantidadFocusGained(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCantidadKeyReleased(evt);
            }
        });

        btAsignar.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.btAsignar.text")); // NOI18N
        btAsignar.setEnabled(false);
        btAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarActionPerformed(evt);
            }
        });

        tfStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfStock.setEnabled(false);
        tfStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfStockFocusGained(evt);
            }
        });
        tfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStockActionPerformed(evt);
            }
        });
        tfStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfStockKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfStockKeyReleased(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jLabel2.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblArticulosAsignar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículo", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(tblArticulosAsignar);

        jButton3.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbconfirmar.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jbconfirmar.text")); // NOI18N
        jbconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconfirmarActionPerformed(evt);
            }
        });
        jbconfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbconfirmarKeyPressed(evt);
            }
        });

        dpFecha.setFormats("dd/MM/yyyy");
        dpFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpFechaActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jLabel4.text")); // NOI18N

        jtfactura.setText(org.openide.util.NbBundle.getMessage(DiagArticuloDepositoAlta.class, "DiagArticuloDepositoAlta.jtfactura.text")); // NOI18N
        jtfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbconfirmar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfactura)))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jXPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jbconfirmar)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAsignar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(122, 122, 122))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyReleased
        /*filtrarListaArticulos();
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jlistArticulosFiltrados.requestFocus();
            jlistArticulosFiltrados.setSelectedIndex(0);
        }*/
    }//GEN-LAST:event_tfDescripcionKeyReleased

    private void jlistArticulosFiltradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosMouseClicked
        actualizarArticuloDesdeListaFiltrada();
    }//GEN-LAST:event_jlistArticulosFiltradosMouseClicked

    private void jlistArticulosFiltradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlistArticulosFiltradosValueChanged
        actualizarArticuloDesdeListaFiltrada();
        cboDeposito.setEnabled(true);
        tfCantidad.setEnabled(true);
    }//GEN-LAST:event_jlistArticulosFiltradosValueChanged

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
        tfCantidad.selectAll();
    }//GEN-LAST:event_tfCantidadFocusGained

    private void tfCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyPressed

    }//GEN-LAST:event_tfCantidadKeyPressed

    private void tfCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyReleased
        if (!Comunes.validarInteger(tfCantidad.getText())) {
            if (tfCantidad.getText().length() > 1) {
                tfCantidad.setText(tfCantidad.getText().substring(0,
                        tfCantidad.getText().length() - 1));
            } else {
                tfCantidad.setText("");
                btAsignar.setEnabled(false);
            }
        } else {
            btAsignar.setEnabled(true);
            //btEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_tfCantidadKeyReleased

    private void btAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarActionPerformed
        asignar();
//        buscarStock();
        this.dispose();
        tfCantidad.setText("");

    }//GEN-LAST:event_btAsignarActionPerformed

    private void tfDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescripcionActionPerformed

    private void tfStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfStockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockFocusGained

    private void tfStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockKeyPressed

    private void tfStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarStock();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            filtrarListaArticulos();
        }
    }//GEN-LAST:event_tfDescripcionKeyPressed

    private void tfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStockActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tblArticulosAsignar.getSelectedRow() != -1) {
            DefaultTableModel dtm = (DefaultTableModel) tblArticulosAsignar.getModel(); //TableProducto es el nombre de mi tabla ;)
            dtm.removeRow(tblArticulosAsignar.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconfirmarActionPerformed
        // TODO add your handling code here:
        if (jlistArticulosFiltrados.getSelectedIndex() != -1) {
            if (Comunes.validarInteger(tfCantidad.getText())) {
                cargarTablaArticulosAsignar((Articulo) jlistArticulosFiltrados.getSelectedValue(), Long.parseLong(tfCantidad.getText()));
                tfCantidad.setText("");
                tfStock.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Debe Ingresar Cantidad a agregar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Articulo");
        }
    }//GEN-LAST:event_jbconfirmarActionPerformed
    private void cargarTablaArticulosAsignar(Articulo art, Long cantidad) {

        // configurarTabla(tblArticulosAsignar);
        try {
            cargarArticuloAsignar(art, cantidad);
        } catch (Exception ex) {

        }
        tblArticulosAsignar.setModel(modeloTablaArticulosAsignar);
    }

    private void cargarArticuloAsignar(Articulo art, Long cantidad) {

        Object[] fila = new Object[2];
        fila[0] = art;
        fila[1] = cantidad;

        modeloTablaArticulosAsignar.addRow(fila);

    }
    private void jbconfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbconfirmarKeyPressed
        cargarTablaArticulosAsignar((Articulo) jlistArticulosFiltrados.getSelectedValue(), Long.parseLong(tfCantidad.getText()));
        tfCantidad.setText("");
        tfStock.setText("");
        tfDescripcion.requestFocus();
    }//GEN-LAST:event_jbconfirmarKeyPressed

    private void dpFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpFechaActionPerformed
        //deshabilitarFecha();
    }//GEN-LAST:event_dpFechaActionPerformed

    private void jtfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfacturaActionPerformed
    public void inicializarComponentes() {
        this.ArticuloDepositoFacade = ArticuloDepositoFacade.getInstance();
        this.ArticuloDepositoMovimientoFacade= ArticuloDepositoMovimientoFacade.getInstance();
        cargarListaArticuloTodos();
        cargarComboBoxDeposito();
        modeloTablaArticulosAsignar = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulosAsignar(modeloTablaArticulosAsignar);
    }

    private void cargarEncabezadosTablaArticulosAsignar(ModeloTablaNoEditable modeloTablaArtAsig) {
        modeloTablaArtAsig.addColumn("Articulo");
        modeloTablaArtAsig.addColumn("Cantidad");

        tblArticulosAsignar.setModel(modeloTablaArtAsig);
        //  Comunes.setOcultarColumnasJTable(tblArticulosAsignar, 0);
    }

    public void filtrarListaArticulos() {
        emf = Persistence.createEntityManagerFactory("ProyectoCuatroPU");
        em = emf.createEntityManager();

        quArticulo = em.createQuery("SELECT a FROM Articulo a WHERE a.descripcion LIKE '%" + tfDescripcion.getText().toUpperCase() + "%'");
        listArticulosFiltrados = quArticulo.getResultList();

        cargarListaArticulos();
    }

    public void cargarListaArticuloTodos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulo.size(); i++) {
            listaModelo.addElement(listArticulo.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void cargarListaArticulos() {
        DefaultListModel listaModelo = new DefaultListModel();
        for (int i = 0; i < listArticulosFiltrados.size(); i++) {
            listaModelo.addElement(listArticulosFiltrados.get(i));
        }
        jlistArticulosFiltrados.setModel(listaModelo);
    }

    public void actualizarArticuloDesdeListaFiltrada() {
        articulo = (Articulo) jlistArticulosFiltrados.getSelectedValue();
        lbDescripcionSeleccionada.setText(articulo.toString());
    }

    public void cargarComboBoxDeposito() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (int i = 0; i < listDeposito.size(); i++) {
            modeloCombo.addElement(listDeposito.get(i));
        }
        cboDeposito.setModel(modeloCombo);
    }

    public void asignar() {

        int fils = tblArticulosAsignar.getRowCount();
        System.out.println("la tabla es " + fils);
        numLote = ArticuloDepositoMovimientoFacade.getInstance().getUltimoNumeroLote()+ 1;
        for (int i = 0; i < fils; i++) {

            articuloDeposito = new ArticuloDeposito();
         
            
            articuloDeposito.setArticulo((Articulo) tblArticulosAsignar.getValueAt(i, 0));
            articuloDeposito.setDeposito((Deposito) cboDeposito.getSelectedItem());
            articuloDeposito.setCantidad((Long) tblArticulosAsignar.getValueAt(i, 1));
            ArticuloDepositoFacade.agregarArticulosAlDeposito(articuloDeposito);
            
            articuloDepositoMovimiento.setArticulo((Articulo) tblArticulosAsignar.getValueAt(i, 0));
            articuloDepositoMovimiento.setDeposito((Deposito) cboDeposito.getSelectedItem());
            articuloDepositoMovimiento.setCantidad((Long) tblArticulosAsignar.getValueAt(i, 1));
            articuloDepositoMovimiento.setNumero(numLote);
            articuloDepositoMovimiento.setFecha(dpFecha.getDate());
            articuloDepositoMovimiento.setFactura(jtfactura.getText());
            
            ArticuloDepositoMovimientoFacade.alta(articuloDepositoMovimiento);
            
            articuloDeposito = new ArticuloDeposito();
            articuloDepositoMovimiento= new ArticuloDepositoMovimiento();
        }

    }

    public void buscarStock() {
        articuloDeposito = ArticuloDepositoFacade.buscar((Articulo) jlistArticulosFiltrados.getSelectedValue(), (Deposito) cboDeposito.getSelectedItem());
        if (articuloDeposito != null) {
            tfStock.setText(articuloDeposito.getCantidad().toString());
        } else {
            tfStock.setText("0");
        }
    }

    public void quitar() {

        articuloDeposito.setArticulo((Articulo) jlistArticulosFiltrados.getSelectedValue());
        articuloDeposito.setDeposito((Deposito) cboDeposito.getSelectedItem());
        articuloDeposito.setCantidad(Long.parseLong(tfCantidad.getText()));
        ArticuloDepositoFacade.eliminarArticulosAlDeposito(articuloDeposito, articuloDeposito.getCantidad());
        articuloDeposito = new ArticuloDeposito();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagArticuloDepositoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagArticuloDepositoAlta dialog = new DiagArticuloDepositoAlta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsignar;
    private javax.swing.JComboBox cboDeposito;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private org.jdesktop.swingx.JXPanel jXPanel7;
    private javax.swing.JButton jbconfirmar;
    private javax.swing.JList jlistArticulosFiltrados;
    private javax.swing.JTextField jtfactura;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDescripcion1;
    private javax.swing.JLabel lbDescripcionSeleccionada;
    private javax.swing.JTable tblArticulosAsignar;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables
}
