/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.listaprecio;

import entidades.articulo.ListaPrecio;
import entidades.articulo.TipoIva;
import entidades.caja.FormaPago;
import facade.GenericoFacade;
import facade.ListaPrecioFacade;
import includes.Comunes;
import static includes.Comunes.redondear;
import java.awt.event.KeyEvent;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author AFerSor
 */
public class DiagListaPrecioEdit<T> extends javax.swing.JDialog {

    private String sLabelButton;
    private int iTipoOp;
    private Boolean rstOperacion;
    private String descripcion;
    private Class<T> entidad;
    private ListaPrecio listaPrecio;
    private List<FormaPago> formasPago;
    private List<ListaPrecio> lstPrecioDentro = new ArrayList<ListaPrecio>();

    /**
     * Creates new form dgAtributoEdit
     */
    public DiagListaPrecioEdit(java.awt.Dialog parent, boolean modal, String titulo, String subTitulo, Class<T> entidad) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
        this.jlSubTitulo.setText(subTitulo);
        this.initComponentes();

        this.setTitle(titulo);

        this.entidad = entidad;
        this.formasPago = new ArrayList<FormaPago>();
        this.lstPrecioDentro = new ArrayList<>();
    }

    private void initComponentes() {
        this.jtfId.setEditable(Boolean.FALSE);
        System.out.println("el subtitulo es" + "ppp" + jlSubTitulo.getText());
        if (jlSubTitulo.getText().equals("  Nuevo")) {
            Comunes.cargarJList(jlListaFuera, ListaPrecioFacade.getInstance().getTodos());
        }

    }//fin initComponentes

    public Boolean getRstOperacion() {
        return rstOperacion;
    }

    public void setRstOperacion(Boolean rstOperacion) {
        this.rstOperacion = rstOperacion;
    }

    public List<FormaPago> getFormasPago() {
        return formasPago;
    }

    public void setFormasPago(List<FormaPago> formasPago) {
        this.formasPago = formasPago;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlSubTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jbAction = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tmargen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlListaDentro = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        quitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlListaFuera = new javax.swing.JList();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));

        jlSubTitulo.setFont(new java.awt.Font("Vrinda", 0, 24)); // NOI18N
        jlSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSubTitulo.setText("titulo");
        jlSubTitulo.setToolTipText("");
        jlSubTitulo.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 2, true));

        jLabel2.setText("Código:");

        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jbAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        jbAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionActionPerformed(evt);
            }
        });

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Margen:");

        tmargen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmargenActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pago"));

        jRadioButton1.setText("Efectivo");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Cheque");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Tarjeta");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Deposito");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Rapipago");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Cuenta Corriente");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton5))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton3))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton4)))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Permite Cambio de Lista"));

        jScrollPane2.setViewportView(jlListaDentro);

        jButton1.setText("agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        quitar.setText("quitar");
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jlListaFuera);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmargen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlSubTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jbAction, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSubTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tmargen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAction, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jbActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionActionPerformed
        this.action();
    }//GEN-LAST:event_jbActionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void tmargenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmargenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmargenActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

        if (jRadioButton1.isSelected()) {
            formasPago.add(FormaPago.EFECTIVO);
        } else {
            formasPago.remove(FormaPago.EFECTIVO);
        }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            formasPago.add(FormaPago.TARJETA);
        } else {
            formasPago.remove(FormaPago.TARJETA);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (jRadioButton3.isSelected()) {
            formasPago.add(FormaPago.CUENTA_CORRIENTE);
        } else {
            formasPago.remove(FormaPago.CUENTA_CORRIENTE);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (jRadioButton4.isSelected()) {
            formasPago.add(FormaPago.CHEQUE);
        } else {
            formasPago.remove(FormaPago.CHEQUE);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        if (jRadioButton5.isSelected()) {
            formasPago.add(FormaPago.DEPOSITO);
        } else {
            formasPago.remove(FormaPago.DEPOSITO);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        if (jRadioButton6.isSelected()) {
            formasPago.add(FormaPago.RAPIPAGO);
        } else {
            formasPago.remove(FormaPago.RAPIPAGO);
        }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarListaPrecios();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        quitarListaPrecios();
    }//GEN-LAST:event_quitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagListaPrecioEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagListaPrecioEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagListaPrecioEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagListaPrecioEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*DiagGenericoEdit dialog = new DiagGenericoEdit(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAction;
    private javax.swing.JButton jbSalir;
    private javax.swing.JList jlListaDentro;
    private javax.swing.JList jlListaFuera;
    private javax.swing.JLabel jlSubTitulo;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JButton quitar;
    private javax.swing.JTextField tmargen;
    // End of variables declaration//GEN-END:variables

    private void action() {

        switch (iTipoOp) {
            case 0:
                this.guardar();
                break;
            case 1:
                this.modificar();
                break;
            case 2:
                this.eliminar();
                break;
        }//fin switch
    }//fin action

    private void agregarListaPrecios() {
        if (jlListaFuera.getSelectedIndex() != -1) {

            lstPrecioDentro.add((ListaPrecio) jlListaFuera.getSelectedValue());
            List<ListaPrecio> listaPrecioFuera = ListaPrecioFacade.getInstance().getTodos();
            listaPrecioFuera.removeAll(lstPrecioDentro);
            Comunes.cargarJList(jlListaFuera, listaPrecioFuera);

            Comunes.cargarJList(jlListaDentro, lstPrecioDentro);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe escoger una Lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void quitarListaPrecios() {
        if (jlListaDentro.getSelectedIndex() != -1) {

            lstPrecioDentro.remove((ListaPrecio) jlListaDentro.getSelectedValue());
            List<ListaPrecio> lstListasFuera = ListaPrecioFacade.getInstance().getTodos();
            lstListasFuera.removeAll(lstPrecioDentro);
            Comunes.cargarJList(jlListaFuera, lstListasFuera);

            Comunes.cargarJList(jlListaDentro, lstPrecioDentro);

        }
    }

    private void guardar() {

        System.out.println("Entro al guardar");
        String sMensaje = "";
        int iTipoMsg = JOptionPane.INFORMATION_MESSAGE;
        try {

            //campos
            /*System.out.println("Entidad: " + entidad);
            TipoIva ti = new TipoIva();

            Method[] methods = ti.getClass().getDeclaredMethods();
            
            System.out.println("cant campos: " + methods.length);
            
            for(int i=0; i < methods.length; i++){
                System.out.println("Nombre del campo: " + 
                        methods[i].getName());
            }//fin for*/
            //nombre del campo
            Class[] cArg = new Class[1];

            cArg[0] = String.class;
            Method campo = null;
            campo = entidad.getDeclaredMethod("setDescripcion", cArg);

            //inyecto el valor del campo
            Object o = entidad.newInstance();
            campo.invoke(o, jtfNombre.getText().trim().toUpperCase());

            cArg[0] = BigDecimal.class;
            campo = entidad.getDeclaredMethod("setMargen", cArg);

            campo.invoke(o, redondear(new BigDecimal(tmargen.getText())));

            cArg[0] = List.class;
            campo = entidad.getDeclaredMethod("setFormasDePago", cArg);

            campo.invoke(o, formasPago);
            cArg[0] = List.class;
            campo = entidad.getDeclaredMethod("setPermiteCambioAListas", cArg);

            campo.invoke(o, lstPrecioDentro);

            System.out.println("paso: " + o.toString());

            GenericoFacade.getInstance().alta(o);

            sMensaje = "El dato fue guardado";
            jtfNombre.setText("");
            this.setRstOperacion(Boolean.TRUE);
        } catch (Exception e) {
            this.setRstOperacion(Boolean.FALSE);
            sMensaje = "Error: " + e.getMessage();
            iTipoMsg = JOptionPane.ERROR_MESSAGE;
        } finally {
            JOptionPane.showMessageDialog(this, sMensaje, "Mensaje", iTipoMsg);
        }
    }//fin guardar

    private void modificar() {

        System.out.println("entro al modificar");

        String sMensaje = "";
        int iTipoMsg = JOptionPane.INFORMATION_MESSAGE;
        try {

            Class[] cArg = new Class[1];
            Method campo = null;

            //id
            cArg[0] = Long.class;
            campo = entidad.getDeclaredMethod("setId", cArg);

            Object o = entidad.newInstance();
            campo.invoke(o, Long.parseLong(jtfId.getText().trim()));

            //Descripcion
            cArg[0] = String.class;
            campo = entidad.getDeclaredMethod("setDescripcion", cArg);

            campo.invoke(o, jtfNombre.getText().toUpperCase().trim());

            //Margen
            cArg[0] = BigDecimal.class;
            campo = entidad.getDeclaredMethod("setMargen", cArg);
            campo.invoke(o, redondear(new BigDecimal(tmargen.getText())));
            //  campo.invoke(o, tmargen.getText().toUpperCase().trim());

            cArg[0] = List.class;
            campo = entidad.getDeclaredMethod("setFormasDePago", cArg);

            campo.invoke(o, formasPago);
            cArg[0] = List.class;
            campo = entidad.getDeclaredMethod("setPermiteCambioAListas", cArg);

            campo.invoke(o, lstPrecioDentro);
            System.out.println("Antes de modificar" + formasPago);
            GenericoFacade.getInstance().modificar(o);

            sMensaje = "El dato fue modificado";
            this.setRstOperacion(Boolean.TRUE);
        } catch (Exception e) {
            this.setRstOperacion(Boolean.FALSE);
            sMensaje = "Error: " + e.getMessage();
            iTipoMsg = JOptionPane.ERROR_MESSAGE;
        } finally {
            JOptionPane.showMessageDialog(this, sMensaje, "Mensaje", iTipoMsg);
        }
    }//fin modificar

    private void eliminar() {
        String sMensaje = "";
        int iTipoMsg = JOptionPane.INFORMATION_MESSAGE;
        try {
            Class[] cArg = new Class[1];
            Method campo = null;

            //id
            cArg[0] = Long.class;
            campo = entidad.getDeclaredMethod("setId", cArg);

            Object o = entidad.newInstance();
            campo.invoke(o, Long.parseLong(jtfId.getText().trim()));

            //Descripcion
            cArg[0] = String.class;
            campo = entidad.getDeclaredMethod("setDescripcion", cArg);

            campo.invoke(o, jtfNombre.getText().toUpperCase().trim());
            //Margen
            cArg[0] = BigDecimal.class;
            campo = entidad.getDeclaredMethod("setMargen", cArg);
            campo.invoke(o, redondear(new BigDecimal(tmargen.getText())));

            cArg[0] = List.class;
            campo = entidad.getDeclaredMethod("setFormasDePago", cArg);

            campo.invoke(o, formasPago);

            GenericoFacade.getInstance().eliminar(o);

            sMensaje = "El dato fue eliminado";
            jtfNombre.setText("");
            tmargen.setText("");
            this.setRstOperacion(Boolean.TRUE);
        } catch (Exception e) {
            this.setRstOperacion(Boolean.FALSE);
            sMensaje = "Error:  No se puede eliminar el Registro porque se esta utilizando";
            iTipoMsg = JOptionPane.ERROR_MESSAGE;
        } finally {
            JOptionPane.showMessageDialog(this, sMensaje, "Mensaje", iTipoMsg);
        }
    }//fin eliminar

    public void definirOperacion(int op) {

        switch (op) {
            case 0:
                this.sLabelButton = "Guardar";
                break;
            case 1:
                this.sLabelButton = "Modificar";
                //this.jtfId.setText(String.valueOf(an.getId()));
                //this.jtfNombre.setText(an.getNombre());

                break;
            case 2:
                this.sLabelButton = "Eliminar";
                //this.jtfId.setText(String.valueOf(an.getId()));
                //this.jtfNombre.setText(an.getNombre());

                break;

        }//fin switch

        iTipoOp = op;
        this.jbAction.setText(sLabelButton);

    }//fin 

    public void cargarCampos(String id, String descripcion, String margen, List formaPago, List listaPrecio) {

        this.jtfId.setText(id);
        this.jtfNombre.setText(descripcion);
        this.tmargen.setText(margen);

        for (int i = 0; i <= formaPago.size() - 1; i++) {

            if (formaPago.get(i).equals(FormaPago.EFECTIVO)) {

                this.jRadioButton1.setSelected(true);
                formasPago.add(FormaPago.EFECTIVO);
            }
            if (formaPago.get(i).equals(FormaPago.TARJETA)) {
                this.jRadioButton2.setSelected(true);
                formasPago.add(FormaPago.TARJETA);
            }
            if (formaPago.get(i).equals(FormaPago.CUENTA_CORRIENTE)) {
                System.out.println("---+++++++++++");
                this.jRadioButton3.setSelected(true);
                formasPago.add(FormaPago.CUENTA_CORRIENTE);
            }
            if (formaPago.get(i).equals(FormaPago.CHEQUE)) {
                this.jRadioButton4.setSelected(true);
                formasPago.add(FormaPago.CHEQUE);
            }
            if (formaPago.get(i).equals(FormaPago.DEPOSITO)) {
                this.jRadioButton5.setSelected(true);
                formasPago.add(FormaPago.DEPOSITO);
            }
            if (formaPago.get(i).equals(FormaPago.RAPIPAGO)) {
                this.jRadioButton6.setSelected(true);
                formasPago.add(FormaPago.RAPIPAGO);
            }
        }
        lstPrecioDentro = listaPrecio;

        Comunes.cargarJList(jlListaDentro, lstPrecioDentro);
        List<ListaPrecio> lstListaPrecioFuera = ListaPrecioFacade.getInstance().getTodos();
        lstListaPrecioFuera.removeAll(lstPrecioDentro);
        Comunes.cargarJList(jlListaFuera, lstListaPrecioFuera);

    }//fin cargarCampos

}
